spring:
  application:
    name: zuul-server
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server.authenticated-collections.svc:80/eureka/
  instance:
    preferIpAddress: true
